### ISSUE TITLE
Can't Share GPS Loc via Text

### ISSUE THREAD

**Issue by Janicki92** [markbucko12341/working-gc-phone#1]
Everything is working great, even the accept/decline calls (once changed to different keybinds)

The problem I have is when you try to text another player, you can hit the right arrow and it gives an option to "Send GPS coordinates".  However, when selecting that option, nothing actually happens.  Any idea on how to fix this?

**Comment by markbucko12341** [comment]
il take a look I tried it yesterday and it worked for me

**Comment by Janicki92** [comment]
Nothing happens when I send it, if it works for you please let me know which resource to update and I’ll try. Thank you for your help!!

________________________________

**Comment by juliiiocesar** [comment]
@Janicki92 

Change in "gcphone/html/static/js/app.js" line 2965

"Envoyer Coord GPS" for "Send GPS Coord"

**Comment by Janicki92** [comment]
Thank you!!! @juliiiocesar
________________________________
